package br.com.hots.modelo.seguranca;

// Generated 22/08/2015 22:43:50 by Hibernate Tools 4.3.1

import java.util.Calendar;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.envers.Audited;
import org.hibernate.validator.constraints.NotEmpty;

/**
 * Perfiltransacao generated by hbm2java
 */
@Cacheable
@Entity
@Audited
@Table(name = "perfiltransacao", catalog = "hots")
public class Perfiltransacao implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private PerfiltransacaoId id;
	private Perfil perfil;
	private Transacao transacao;
	private Date dataCadastro;
	private String flagAtivo;

	public Perfiltransacao() {
	}

	public Perfiltransacao(PerfiltransacaoId id, Perfil perfil,
			Transacao transacao, Date dataCadastro, String flagAtivo) {
		this.id = id;
		this.perfil = perfil;
		this.transacao = transacao;
		this.dataCadastro = dataCadastro;
		this.flagAtivo = flagAtivo;
	}
	
	@PrePersist
	public void atualizaCamposParaInsercao() {
		setDataCadastro(Calendar.getInstance().getTime());
	}

	@PreUpdate
	public void atualizaCamposParaAtualizacao() {
		setDataCadastro(Calendar.getInstance().getTime());
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idPerfil", column = @Column(name = "idPerfil", nullable = false)),
			@AttributeOverride(name = "idTransacao", column = @Column(name = "idTransacao", nullable = false)) })
	public PerfiltransacaoId getId() {
		return this.id;
	}

	public void setId(PerfiltransacaoId id) {
		this.id = id;
	}

	@NotEmpty(message = "O campo perfil é obrigatório")
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idPerfil", nullable = false, insertable = false, updatable = false)
	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTransacao", nullable = false, insertable = false, updatable = false)
	public Transacao getTransacao() {
		return this.transacao;
	}

	public void setTransacao(Transacao transacao) {
		this.transacao = transacao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataCadastro", nullable = false, length = 19)
	public Date getDataCadastro() {
		return this.dataCadastro;
	}

	public void setDataCadastro(Date dataCadastro) {
		this.dataCadastro = dataCadastro;
	}

	@Column(name = "flagAtivo", nullable = false, length = 1)
	public String getFlagAtivo() {
		return this.flagAtivo;
	}

	public void setFlagAtivo(String flagAtivo) {
		this.flagAtivo = flagAtivo;
	}

}
