package br.com.hots.modelo.seguranca;

// Generated 15/08/2015 19:23:14 by Hibernate Tools 4.3.1

import java.util.Calendar;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Perfiltransacao generated by hbm2java
 */
@Entity
@Table(name = "perfiltransacao", catalog = "hots")
public class Perfiltransacao implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private PerfiltransacaoId id;
	private Perfil perfil;
	private Transacao transacao;
	private Calendar dataCadastro;
	private String flagAtivo;

	public Perfiltransacao() {
	}

	public Perfiltransacao(PerfiltransacaoId id, Perfil perfil,
			Transacao transacao, Calendar dataCadastro, String flagAtivo) {
		this.id = id;
		this.perfil = perfil;
		this.transacao = transacao;
		this.dataCadastro = dataCadastro;
		this.flagAtivo = flagAtivo;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idPefil", column = @Column(name = "idPefil", nullable = false)),
			@AttributeOverride(name = "idTransacao", column = @Column(name = "idTransacao", nullable = false)) })
	public PerfiltransacaoId getId() {
		return this.id;
	}

	public void setId(PerfiltransacaoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idPefil", nullable = false, insertable = false, updatable = false)
	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTransacao", nullable = false, insertable = false, updatable = false)
	public Transacao getTransacao() {
		return this.transacao;
	}

	public void setTransacao(Transacao transacao) {
		this.transacao = transacao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataCadastro", nullable = false, length = 19)
	public Calendar getDataCadastro() {
		return this.dataCadastro;
	}

	public void setDataCadastro(Calendar dataCadastro) {
		this.dataCadastro = dataCadastro;
	}

	@Column(name = "flagAtivo", nullable = false, length = 1)
	public String getFlagAtivo() {
		return this.flagAtivo;
	}

	public void setFlagAtivo(String flagAtivo) {
		this.flagAtivo = flagAtivo;
	}

}