package br.com.hots.modelo.seguranca;

// Generated 22/08/2015 22:43:50 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PerfiltransacaoId generated by hbm2java
 */
@Embeddable
public class PerfiltransacaoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idPerfil;
	private Integer idTransacao;

	public PerfiltransacaoId() {
	}

	public PerfiltransacaoId(Integer idPerfil, Integer idTransacao) {
		this.idPerfil = idPerfil;
		this.idTransacao = idTransacao;
	}

	@Column(name = "idPerfil", nullable = false)
	public Integer getIdPerfil() {
		return this.idPerfil;
	}

	public void setIdPerfil(Integer idPerfil) {
		this.idPerfil = idPerfil;
	}

	@Column(name = "idTransacao", nullable = false)
	public Integer getIdTransacao() {
		return this.idTransacao;
	}

	public void setIdTransacao(Integer idTransacao) {
		this.idTransacao = idTransacao;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PerfiltransacaoId))
			return false;
		PerfiltransacaoId castOther = (PerfiltransacaoId) other;

		return (this.getIdPerfil() == castOther.getIdPerfil())
				&& (this.getIdTransacao() == castOther.getIdTransacao());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdPerfil();
		result = 37 * result + this.getIdTransacao();
		return result;
	}

}
