package br.com.hots.modelo.seguranca;

// Generated 22/08/2015 22:43:50 by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Calendar;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.envers.Audited;

/**
 * Perfil generated by hbm2java
 */
@Cacheable
@Entity
@Audited
@Table(name = "perfil", catalog = "hots", uniqueConstraints = @UniqueConstraint(columnNames = "dePerfil"))
public class Perfil implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idPerfil;
	private String dePerfil;
	private String observacao;
	private Date dataCadastro;
	private String flagAtivo;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);
	private Set<Perfiltransacao> perfiltransacaos = new HashSet<Perfiltransacao>(0);

	public Perfil() {
	}

	public Perfil(Integer idPerfil, String dePerfil, Date dataCadastro,
			String flagAtivo) {
		this.idPerfil = idPerfil;
		this.dePerfil = dePerfil;
		this.dataCadastro = dataCadastro;
		this.flagAtivo = flagAtivo;
	}

	public Perfil(Integer idPerfil, String dePerfil, String observacao,
			Date dataCadastro, String flagAtivo, Set<Usuario> usuarios,
			Set<Perfiltransacao> perfiltransacaos) {
		this.idPerfil = idPerfil;
		this.dePerfil = dePerfil;
		this.observacao = observacao;
		this.dataCadastro = dataCadastro;
		this.flagAtivo = flagAtivo;
		this.usuarios = usuarios;
		this.perfiltransacaos = perfiltransacaos;
	}
	
	@PrePersist
	public void atualizaCamposParaInsercao() {
		setDataCadastro(Calendar.getInstance().getTime());
		setFlagAtivo("S");
	}

	@PreUpdate
	public void atualizaCamposParaAtualizacao() {
		setDataCadastro(Calendar.getInstance().getTime());
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idPerfil", unique = true, nullable = false)
	public Integer getIdPerfil() {
		return this.idPerfil;
	}

	public void setIdPerfil(Integer idPerfil) {
		this.idPerfil = idPerfil;
	}

	@Column(name = "dePerfil", unique = true, nullable = false, length = 100)
	public String getDePerfil() {
		return this.dePerfil;
	}

	public void setDePerfil(String dePerfil) {
		this.dePerfil = dePerfil;
	}

	@Column(name = "observacao", length = 500)
	public String getObservacao() {
		return this.observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataCadastro", nullable = false, length = 19)
	public Date getDataCadastro() {
		return this.dataCadastro;
	}

	public void setDataCadastro(Date dataCadastro) {
		this.dataCadastro = dataCadastro;
	}

	@Column(name = "flagAtivo", nullable = false, length = 1)
	public String getFlagAtivo() {
		return this.flagAtivo;
	}

	public void setFlagAtivo(String flagAtivo) {
		this.flagAtivo = flagAtivo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
	public Set<Perfiltransacao> getPerfiltransacaos() {
		return this.perfiltransacaos;
	}

	public void setPerfiltransacaos(Set<Perfiltransacao> perfiltransacaos) {
		this.perfiltransacaos = perfiltransacaos;
	}

}
