package br.com.hots.modelo.seguranca;

// Generated 15/08/2015 19:23:14 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsuarioperfilId generated by hbm2java
 */
@Embeddable
public class UsuarioperfilId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idUsuario;
	private Integer idPerfil;

	public UsuarioperfilId() {
	}

	public UsuarioperfilId(Integer idUsuario, Integer idPerfil) {
		this.idUsuario = idUsuario;
		this.idPerfil = idPerfil;
	}

	@Column(name = "idUsuario", nullable = false)
	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "idPefil", nullable = false)
	public Integer getIdPerfil() {
		return this.idPerfil;
	}

	public void setIdPerfil(Integer idPerfil) {
		this.idPerfil = idPerfil;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuarioperfilId))
			return false;
		UsuarioperfilId castOther = (UsuarioperfilId) other;

		return (this.getIdUsuario() == castOther.getIdUsuario())
				&& (this.getIdPerfil() == castOther.getIdPerfil());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdUsuario();
		result = 37 * result + this.getIdPerfil();
		return result;
	}

}