package br.com.hots.modelo.seguranca;

// Generated 15/08/2015 19:23:14 by Hibernate Tools 4.3.1

import java.util.Calendar;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuarioperfil generated by hbm2java
 */
@Entity
@Table(name = "usuarioperfil", catalog = "hots")
public class Usuarioperfil implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private UsuarioperfilId id;
	private Perfil perfil;
	private Usuario usuario;
	private Calendar dataCadastro;
	private String flagAtivo;

	public Usuarioperfil() {
	}

	public Usuarioperfil(UsuarioperfilId id, Perfil perfil, Usuario usuario,
			Calendar dataCadastro, String flagAtivo) {
		this.id = id;
		this.perfil = perfil;
		this.usuario = usuario;
		this.dataCadastro = dataCadastro;
		this.flagAtivo = flagAtivo;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idUsuario", column = @Column(name = "idUsuario", nullable = false)),
			@AttributeOverride(name = "idPerfil", column = @Column(name = "idPerfil", nullable = false)) })
	public UsuarioperfilId getId() {
		return this.id;
	}

	public void setId(UsuarioperfilId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idPefil", nullable = false, insertable = false, updatable = false)
	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idUsuario", nullable = false, insertable = false, updatable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataCadastro", nullable = false, length = 19)
	public Calendar getDataCadastro() {
		return this.dataCadastro;
	}

	public void setDataCadastro(Calendar dataCadastro) {
		this.dataCadastro = dataCadastro;
	}

	@Column(name = "flagAtivo", nullable = false, length = 1)
	public String getFlagAtivo() {
		return this.flagAtivo;
	}

	public void setFlagAtivo(String flagAtivo) {
		this.flagAtivo = flagAtivo;
	}

}