package br.com.hots.modelo;

// Generated 15/08/2015 19:23:14 by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Calendar;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Auditoriarevisao generated by hbm2java
 */
@Entity
@Table(name = "auditoriarevisao", catalog = "hots")
public class Auditoriarevisao implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idRevisao;
	private Calendar dataRevisao;
	private String login;

	public Auditoriarevisao() {
	}

	public Auditoriarevisao(Calendar dataRevisao, String login) {
		this.dataRevisao = dataRevisao;
		this.login = login;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idRevisao", unique = true, nullable = false)
	public Integer getIdRevisao() {
		return this.idRevisao;
	}

	public void setIdRevisao(Integer idRevisao) {
		this.idRevisao = idRevisao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataRevisao", length = 19)
	public Calendar getDataRevisao() {
		return this.dataRevisao;
	}

	public void setDataRevisao(Calendar dataRevisao) {
		this.dataRevisao = dataRevisao;
	}

	@Column(name = "login")
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

}
