package br.com.hots.modelo;

// Generated 18/07/2015 21:46:33 by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Calendar;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.envers.Audited;
import org.hibernate.envers.NotAudited;

/**
 * Heroi generated by hbm2java
 */
@Audited
@Entity
@Table(name = "heroi", catalog = "hots", uniqueConstraints = @UniqueConstraint(columnNames = "nome"))
public class Heroi implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idHeroi;
	private Funcao funcao;
	private Universo universo;
	private String nome;
	private Integer dano;
	private Integer utilidade;
	private Integer sobrevivencia;
	private Integer complexidade;
	private Calendar dataCadastro;
	private String flagAtivo;
	private Set<Time> times = new HashSet<Time>(0);

	public Heroi() {
	}

	public Heroi(Funcao funcao, Universo universo, String nome, Integer dano,
			Integer utilidade, Integer sobrevivencia, Integer complexidade,
			Calendar dataCadastro, String flagAtivo) {
		this.funcao = funcao;
		this.universo = universo;
		this.nome = nome;
		this.dano = dano;
		this.utilidade = utilidade;
		this.sobrevivencia = sobrevivencia;
		this.complexidade = complexidade;
		this.dataCadastro = dataCadastro;
		this.flagAtivo = flagAtivo;
	}

	public Heroi(Funcao funcao, Universo universo, String nome, Integer dano,
			Integer utilidade, Integer sobrevivencia, Integer complexidade,
			Calendar dataCadastro, String flagAtivo, Set<Time> times) {
		this.funcao = funcao;
		this.universo = universo;
		this.nome = nome;
		this.dano = dano;
		this.utilidade = utilidade;
		this.sobrevivencia = sobrevivencia;
		this.complexidade = complexidade;
		this.dataCadastro = dataCadastro;
		this.flagAtivo = flagAtivo;
		this.times = times;
	}
	
	@PrePersist
	public void preparaCamposParaInsercao() {
		setDataCadastro(Calendar.getInstance());
		setFlagAtivo("S");
	}

	@PreUpdate
	public void preparaCamposParaAtualizacao() {
		setDataCadastro(Calendar.getInstance());
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idHeroi", unique = true, nullable = false)
	public Integer getIdHeroi() {
		return this.idHeroi;
	}

	public void setIdHeroi(Integer idHeroi) {
		this.idHeroi = idHeroi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idFuncao", nullable = false)
	public Funcao getFuncao() {
		return this.funcao;
	}

	public void setFuncao(Funcao funcao) {
		this.funcao = funcao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idUniverso", nullable = false)
	public Universo getUniverso() {
		return this.universo;
	}

	public void setUniverso(Universo universo) {
		this.universo = universo;
	}

	@Column(name = "nome", unique = true, nullable = false, length = 100)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "dano", nullable = false)
	public Integer getDano() {
		return this.dano;
	}

	public void setDano(Integer dano) {
		this.dano = dano;
	}

	@Column(name = "utilidade", nullable = false)
	public Integer getUtilidade() {
		return this.utilidade;
	}

	public void setUtilidade(Integer utilidade) {
		this.utilidade = utilidade;
	}

	@Column(name = "sobrevivencia", nullable = false)
	public Integer getSobrevivencia() {
		return this.sobrevivencia;
	}

	public void setSobrevivencia(Integer sobrevivencia) {
		this.sobrevivencia = sobrevivencia;
	}

	@Column(name = "complexidade", nullable = false)
	public Integer getComplexidade() {
		return this.complexidade;
	}

	public void setComplexidade(Integer complexidade) {
		this.complexidade = complexidade;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataCadastro", nullable = false, length = 19)
	public Calendar getDataCadastro() {
		return this.dataCadastro;
	}

	public void setDataCadastro(Calendar dataCadastro) {
		this.dataCadastro = dataCadastro;
	}

	@Column(name = "flagAtivo", nullable = false, length = 1)
	public String getFlagAtivo() {
		return this.flagAtivo;
	}

	public void setFlagAtivo(String flagAtivo) {
		this.flagAtivo = flagAtivo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "heroi")
	@NotAudited
	public Set<Time> getTimes() {
		return this.times;
	}

	public void setTimes(Set<Time> times) {
		this.times = times;
	}

}
