package br.com.hots.modelo;

// Generated 18/07/2015 21:46:33 by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Calendar;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.envers.Audited;
import org.hibernate.envers.NotAudited;

/**
 * Jogador generated by hbm2java
 */
@Audited
@Entity
@Table(name = "jogador", catalog = "hots")
public class Jogador implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idJogador;
	private String apelido;
	private String nome;
	private String email;
	private Calendar dataCadastro;
	private String flagAtivo;
	private Set<Time> times = new HashSet<Time>(0);

	public Jogador() {
	}

	public Jogador(String apelido, String nome, String email,
			Calendar dataCadastro, String flagAtivo) {
		this.apelido = apelido;
		this.nome = nome;
		this.email = email;
		this.dataCadastro = dataCadastro;
		this.flagAtivo = flagAtivo;
	}

	public Jogador(String apelido, String nome, String email,
			Calendar dataCadastro, String flagAtivo, Set<Time> times) {
		this.apelido = apelido;
		this.nome = nome;
		this.email = email;
		this.dataCadastro = dataCadastro;
		this.flagAtivo = flagAtivo;
		this.times = times;
	}

	@PrePersist
	public void atualizaCamposParaInsercao() {
		setDataCadastro(Calendar.getInstance());
		setFlagAtivo("S");
	}

	@PreUpdate
	public void atualizaCamposParaAtualizacao() {
		setDataCadastro(Calendar.getInstance());
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idJogador", unique = true, nullable = false)
	public Integer getIdJogador() {
		return this.idJogador;
	}

	public void setIdJogador(Integer idJogador) {
		this.idJogador = idJogador;
	}

	@Column(name = "apelido", nullable = false, length = 100)
	public String getApelido() {
		return this.apelido;
	}

	public void setApelido(String apelido) {
		this.apelido = apelido;
	}

	@Column(name = "nome", nullable = false, length = 100)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataCadastro", nullable = false, length = 19)
	public Calendar getDataCadastro() {
		return this.dataCadastro;
	}

	public void setDataCadastro(Calendar dataCadastro) {
		this.dataCadastro = dataCadastro;
	}

	@Column(name = "flagAtivo", nullable = false, length = 1)
	public String getFlagAtivo() {
		return this.flagAtivo;
	}

	public void setFlagAtivo(String flagAtivo) {
		this.flagAtivo = flagAtivo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jogador")
	@NotAudited
	public Set<Time> getTimes() {
		return this.times;
	}

	public void setTimes(Set<Time> times) {
		this.times = times;
	}

}