package br.com.hots.modelo;

// Generated 18/07/2015 21:46:33 by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Calendar;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Partida generated by hbm2java
 */
@Entity
@Table(name = "partida", catalog = "hots")
public class Partida implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idPartida;
	private Time timeByIdTimeVencedor;
	private Time timeByIdTime1;
	private Time timeByIdTime2;
	private Integer mortes;
	private Calendar dataCadastro;
	private String flagAtivo;

	public Partida() {
	}

	public Partida(Time timeByIdTime1, Time timeByIdTime2, Calendar dataCadastro,
			String flagAtivo) {
		this.timeByIdTime1 = timeByIdTime1;
		this.timeByIdTime2 = timeByIdTime2;
		this.dataCadastro = dataCadastro;
		this.flagAtivo = flagAtivo;
	}

	public Partida(Time timeByIdTimeVencedor, Time timeByIdTime1,
			Time timeByIdTime2, Integer mortes, Calendar dataCadastro,
			String flagAtivo) {
		this.timeByIdTimeVencedor = timeByIdTimeVencedor;
		this.timeByIdTime1 = timeByIdTime1;
		this.timeByIdTime2 = timeByIdTime2;
		this.mortes = mortes;
		this.dataCadastro = dataCadastro;
		this.flagAtivo = flagAtivo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idPartida", unique = true, nullable = false)
	public Integer getIdPartida() {
		return this.idPartida;
	}

	public void setIdPartida(Integer idPartida) {
		this.idPartida = idPartida;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTimeVencedor")
	public Time getTimeByIdTimeVencedor() {
		return this.timeByIdTimeVencedor;
	}

	public void setTimeByIdTimeVencedor(Time timeByIdTimeVencedor) {
		this.timeByIdTimeVencedor = timeByIdTimeVencedor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTime1", nullable = false)
	public Time getTimeByIdTime1() {
		return this.timeByIdTime1;
	}

	public void setTimeByIdTime1(Time timeByIdTime1) {
		this.timeByIdTime1 = timeByIdTime1;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTime2", nullable = false)
	public Time getTimeByIdTime2() {
		return this.timeByIdTime2;
	}

	public void setTimeByIdTime2(Time timeByIdTime2) {
		this.timeByIdTime2 = timeByIdTime2;
	}

	@Column(name = "mortes")
	public Integer getMortes() {
		return this.mortes;
	}

	public void setMortes(Integer mortes) {
		this.mortes = mortes;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataCadastro", nullable = false, length = 19)
	public Calendar getDataCadastro() {
		return this.dataCadastro;
	}

	public void setDataCadastro(Calendar dataCadastro) {
		this.dataCadastro = dataCadastro;
	}

	@Column(name = "flagAtivo", nullable = false, length = 1)
	public String getFlagAtivo() {
		return this.flagAtivo;
	}

	public void setFlagAtivo(String flagAtivo) {
		this.flagAtivo = flagAtivo;
	}

}
