package br.com.hots.modelo;

// Generated 15/08/2015 19:23:14 by Hibernate Tools 4.3.1

import java.util.Calendar;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Perfil generated by hbm2java
 */
@Entity
@Table(name = "perfil", catalog = "hots", uniqueConstraints = @UniqueConstraint(columnNames = "dePerfil"))
public class Perfil implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idPerfil;
	private String dePerfil;
	private String observacao;
	private Calendar dataCadastro;
	private String flagAtivo;
	private Set<Usuarioperfil> usuarioperfils = new HashSet<Usuarioperfil>(0);
	private Set<Perfiltransacao> perfiltransacaos = new HashSet<Perfiltransacao>(0);

	public Perfil() {
	}

	public Perfil(Integer idPerfil, String dePerfil, Calendar dataCadastro,
			String flagAtivo) {
		this.idPerfil = idPerfil;
		this.dePerfil = dePerfil;
		this.dataCadastro = dataCadastro;
		this.flagAtivo = flagAtivo;
	}

	public Perfil(Integer idPerfil, String dePerfil, String observacao,
			Calendar dataCadastro, String flagAtivo,
			Set<Usuarioperfil> usuarioperfils,
			Set<Perfiltransacao> perfiltransacaos) {
		this.idPerfil = idPerfil;
		this.dePerfil = dePerfil;
		this.observacao = observacao;
		this.dataCadastro = dataCadastro;
		this.flagAtivo = flagAtivo;
		this.usuarioperfils = usuarioperfils;
		this.perfiltransacaos = perfiltransacaos;
	}

	@Id
	@Column(name = "idPerfil", unique = true, nullable = false)
	public Integer getIdPerfil() {
		return this.idPerfil;
	}

	public void setIdPerfil(Integer idPerfil) {
		this.idPerfil = idPerfil;
	}

	@Column(name = "dePerfil", unique = true, nullable = false, length = 100)
	public String getDePerfil() {
		return this.dePerfil;
	}

	public void setDePerfil(String dePerfil) {
		this.dePerfil = dePerfil;
	}

	@Column(name = "observacao", length = 500)
	public String getObservacao() {
		return this.observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataCadastro", nullable = false, length = 19)
	public Calendar getDataCadastro() {
		return this.dataCadastro;
	}

	public void setDataCadastro(Calendar dataCadastro) {
		this.dataCadastro = dataCadastro;
	}

	@Column(name = "flagAtivo", nullable = false, length = 1)
	public String getFlagAtivo() {
		return this.flagAtivo;
	}

	public void setFlagAtivo(String flagAtivo) {
		this.flagAtivo = flagAtivo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
	public Set<Usuarioperfil> getUsuarioperfils() {
		return this.usuarioperfils;
	}

	public void setUsuarioperfils(Set<Usuarioperfil> usuarioperfils) {
		this.usuarioperfils = usuarioperfils;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
	public Set<Perfiltransacao> getPerfiltransacaos() {
		return this.perfiltransacaos;
	}

	public void setPerfiltransacaos(Set<Perfiltransacao> perfiltransacaos) {
		this.perfiltransacaos = perfiltransacaos;
	}

}