package br.com.hots.modelo;

// Generated 15/08/2015 19:23:14 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PerfiltransacaoId generated by hbm2java
 */
@Embeddable
public class PerfiltransacaoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idPefil;
	private Integer idTransacao;

	public PerfiltransacaoId() {
	}

	public PerfiltransacaoId(Integer idPefil, Integer idTransacao) {
		this.idPefil = idPefil;
		this.idTransacao = idTransacao;
	}

	@Column(name = "idPefil", nullable = false)
	public Integer getIdPefil() {
		return this.idPefil;
	}

	public void setIdPefil(Integer idPefil) {
		this.idPefil = idPefil;
	}

	@Column(name = "idTransacao", nullable = false)
	public Integer getIdTransacao() {
		return this.idTransacao;
	}

	public void setIdTransacao(Integer idTransacao) {
		this.idTransacao = idTransacao;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PerfiltransacaoId))
			return false;
		PerfiltransacaoId castOther = (PerfiltransacaoId) other;

		return (this.getIdPefil() == castOther.getIdPefil())
				&& (this.getIdTransacao() == castOther.getIdTransacao());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdPefil();
		result = 37 * result + this.getIdTransacao();
		return result;
	}

}