package br.com.hots.modelo.jogo;

// Generated 22/08/2015 22:43:50 by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Calendar;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.envers.Audited;
import org.hibernate.validator.constraints.NotEmpty;

/**
 * Funcao generated by hbm2java
 */
@Audited
@Entity
@Table(name = "funcao", catalog = "hots", uniqueConstraints = @UniqueConstraint(columnNames = "deFuncao"))
public class Funcao implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idFuncao;
	private String deFuncao;
	private Date dataCadastro;
	private String flagAtivo;
	private Set<Heroi> herois = new HashSet<Heroi>(0);

	public Funcao() {
	}

	public Funcao(String deFuncao, Date dataCadastro, String flagAtivo) {
		this.deFuncao = deFuncao;
		this.dataCadastro = dataCadastro;
		this.flagAtivo = flagAtivo;
	}

	public Funcao(String deFuncao, Date dataCadastro, String flagAtivo,
			Set<Heroi> herois) {
		this.deFuncao = deFuncao;
		this.dataCadastro = dataCadastro;
		this.flagAtivo = flagAtivo;
		this.herois = herois;
	}

	@PrePersist
	public void atualizaCamposParaInsercao() {
		setDataCadastro(Calendar.getInstance().getTime());
		setFlagAtivo("S");
	}

	@PreUpdate
	public void atualizaCamposParaAtualizacao() {
		setDataCadastro(Calendar.getInstance().getTime());
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idFuncao", unique = true, nullable = false)
	public Integer getIdFuncao() {
		return this.idFuncao;
	}

	public void setIdFuncao(Integer idFuncao) {
		this.idFuncao = idFuncao;
	}

	@NotEmpty(message = "O campo função é obrigatório")
	@Column(name = "deFuncao", unique = true, nullable = false, length = 100)
	public String getDeFuncao() {
		return this.deFuncao;
	}

	public void setDeFuncao(String deFuncao) {
		this.deFuncao = deFuncao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataCadastro", nullable = false, length = 19)
	public Date getDataCadastro() {
		return this.dataCadastro;
	}

	public void setDataCadastro(Date dataCadastro) {
		this.dataCadastro = dataCadastro;
	}

	@Column(name = "flagAtivo", nullable = false, length = 1)
	public String getFlagAtivo() {
		return this.flagAtivo;
	}

	public void setFlagAtivo(String flagAtivo) {
		this.flagAtivo = flagAtivo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "funcao")
	public Set<Heroi> getHerois() {
		return this.herois;
	}

	public void setHerois(Set<Heroi> herois) {
		this.herois = herois;
	}

}
